name: Rust

on: [workflow_call]

env:
  CARGO_TERM_COLOR: always

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose
    
    - name: Build
      run: cargo test --verbose
    
    - name: Run clippy
      run: cargo clippy --verbose
  
  coverage:
    uses: ./.github/workflows/coverage.yml
    needs: [build]